#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct AjaxDataSource <: iAjaxDataSource

    adapter :: Union{Nothing, iCustomJS} = nothing

    content_type :: String = "application/json"

    data :: Model.DataDict = Model.DataDict()

    data_url :: String

    http_headers :: Dict{String, String} = Dict{String, String}()

    if_modified :: Bool = false

    max_size :: Union{Nothing, Int64} = nothing

    method :: Model.EnumType{(:POST, :GET)} = :POST

    mode :: Model.EnumType{(:replace, :append)} = :replace

    polling_interval :: Union{Nothing, Int64} = nothing

    selected :: Model.ReadOnly{iSelection} = Selection()

    selection_policy :: iSelectionPolicy = UnionRenderers()
end
export AjaxDataSource
