#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Arc <: iArc

    decorations :: Vector{iDecoration} = iDecoration[]

    direction :: Model.EnumType{(:clock, :anticlock)} = :anticlock

    finish_angle :: Model.AngleSpec = "end_angle"

    line_alpha :: Model.AlphaSpec = 1.0

    line_cap :: Model.LineCapSpec = :butt

    line_color :: Model.ColorSpec = "#000000"

    line_dash :: Model.DashPatternSpec = Int64[]

    line_dash_offset :: Model.IntSpec = 0

    line_join :: Model.LineJoinSpec = :bevel

    line_width :: Model.NumberSpec = 1.0

    radius :: Model.DistanceSpec = "radius"

    start_angle :: Model.AngleSpec = "start_angle"

    x :: Model.NumberSpec = "x"

    y :: Model.NumberSpec = "y"
end
export Arc
glyphargs(::Type{Arc}) = (:x, :y, :radius, :start_angle, :finish_angle, :direction)
