#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Band <: iBand

    base :: Model.UnitsSpec = "base"

    coordinates :: Union{Nothing, iCoordinateMapping} = nothing

    dimension :: Model.EnumType{(:width, :height)} = :height

    fill_alpha :: Model.Percent = 0.4

    fill_color :: Union{Nothing, Model.Color} = "#FFF9BA"

    group :: Union{Nothing, iRendererGroup} = nothing

    level :: Model.EnumType{(:image, :underlay, :glyph, :guide, :annotation, :overlay)} = :image

    line_alpha :: Model.Percent = 0.3

    line_cap :: Model.LineCap = :butt

    line_color :: Union{Nothing, Model.Color} = "#CCCCCC"

    line_dash :: Model.DashPattern = Int64[]

    line_dash_offset :: Int64 = 0

    line_join :: Model.LineJoin = :bevel

    line_width :: Float64 = 1.0

    lower :: Model.UnitsSpec = "lower"

    source :: iDataSource = ColumnDataSource()

    upper :: Model.UnitsSpec = "upper"

    visible :: Bool = true

    x_range_name :: String = "default"

    y_range_name :: String = "default"
end
export Band
