#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct BBoxTileSource <: iBBoxTileSource

    attribution :: String = ""

    extra_url_vars :: Dict{String, Any} = Dict{String, Any}()

    initial_resolution :: Union{Nothing, Float64} = nothing

    max_zoom :: Int64 = 30

    min_zoom :: Int64 = 0

    snap_to_zoom :: Bool = false

    tile_size :: Int64 = 256

    url :: String = ""

    use_latlon :: Bool = false

    wrap_around :: Bool = true

    x_origin_offset :: Float64 = required

    y_origin_offset :: Float64 = required
end
export BBoxTileSource
glyphargs(::Type{BBoxTileSource}) = (:url, :tile_size, :min_zoom, :max_zoom, :x_origin_offset, :y_origin_offset, :extra_url_vars, :initial_resolution)
