#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct BinnedTicker <: iBinnedTicker

    mapper :: iScanningColorMapper

    num_major_ticks :: Union{Int64, Model.EnumType{(:auto,)}} = 8
end
