#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct BoxSelectTool <: iBoxSelectTool

    description :: Union{Nothing, String} = nothing

    dimensions :: Model.EnumType{(:width, :height, :both)} = :both

    icon :: Union{Nothing, Model.ToolIconValue} = nothing

    mode :: Model.EnumType{(:replace, :append, :intersect, :subtract)} = :replace

    origin :: Model.EnumType{(:corner, :center)} = :corner

    overlay :: iBoxAnnotation = BoxAnnotation(left_units = "canvas", line_width = 2, fill_alpha = 0.5, bottom_units = "canvas", line_dash = Any[4, 4], level = "overlay", visible = false, syncable = false, top_units = "canvas", line_alpha = 1.0, fill_color = "lightgrey", line_color = "black", right_units = "canvas")

    renderers :: Union{Model.EnumType{(:auto,)}, Vector{iDataRenderer}} = :auto

    select_every_mousemove :: Bool = false
end
export BoxSelectTool
