#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct BoxZoomTool <: iBoxZoomTool

    description :: Union{Nothing, String} = nothing

    dimensions :: Model.EnumType{(:width, :height, :both)} = :both

    match_aspect :: Bool = false

    origin :: Model.EnumType{(:corner, :center)} = :corner

    overlay :: iBoxAnnotation = BoxAnnotation()
end
export BoxZoomTool
