#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct BuiltinIcon <: iBuiltinIcon

    color :: Model.Color = "#808080"

    icon_name :: Union{String, Model.ToolIcon}

    size :: Union{Model.FontSize, Int64} = "1em"
end
export BuiltinIcon
