#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct CategoricalColorMapper <: iCategoricalColorMapper

    factors :: Union{Vector{String}, Vector{Tuple{String, String}}, Vector{Tuple{String, String, String}}}

    finish :: Union{Nothing, Int64} = nothing

    nan_color :: Model.Color = "#808080"

    palette :: Vector{Model.Color}

    start :: Int64 = 0
end
export CategoricalColorMapper
