#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct CDSView <: iCDSView

    filters :: Vector{iFilter} = iFilter[]

    source :: iColumnarDataSource
end
export CDSView
