#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct ContourRenderer <: iContourRenderer

    coordinates :: Union{Nothing, iCoordinateMapping} = nothing

    fill_renderer :: iGlyphRenderer

    group :: Union{Nothing, iRendererGroup} = nothing

    level :: Model.EnumType{(:image, :underlay, :glyph, :guide, :annotation, :overlay)} = :image

    levels :: Vector{Float64} = Float64[]

    line_renderer :: iGlyphRenderer

    visible :: Bool = true

    x_range_name :: String = "default"

    y_range_name :: String = "default"
end
export ContourRenderer
