#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct CrosshairTool <: iCrosshairTool

    description :: Union{Nothing, String} = nothing

    dimensions :: Model.EnumType{(:width, :height, :both)} = :both

    icon :: Union{Nothing, Model.ToolIconValue} = nothing

    line_alpha :: Model.Percent = 1.0

    line_color :: Model.Color = "#000000"

    line_width :: Float64 = 1.0

    toggleable :: Bool = true
end
export CrosshairTool
