#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct CustomJSHover <: iCustomJSHover

    args :: Dict{String, iModel} = Dict{String, iModel}()

    code :: String = ""
end
