#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct CustomJSHover <: iCustomJSHover

    args :: Dict{String, Any} = Dict{String, Any}()

    code :: String = ""
end
export CustomJSHover
