#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct CustomJSFilter <: iCustomJSFilter

    args :: Dict{Model.RestrictedKey{(:source,)}, Any} = Dict{Symbol, Any}()

    code :: String = ""
end
export CustomJSFilter
