#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct CustomJSTickFormatter <: iCustomJSTickFormatter

    args :: Dict{String, Any} = Dict{String, Any}()

    code :: String = ""
end
export CustomJSTickFormatter
