#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct CustomJSTransform <: iCustomJSTransform

    args :: Dict{String, Any} = Dict{String, Any}()

    func :: String = ""

    v_func :: String = ""
end
export CustomJSTransform
