#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct DataTable <: iDataTable

    align :: Union{Tuple{Model.EnumType{(:start, :center, :end)}, Model.EnumType{(:start, :center, :end)}}, Model.EnumType{(:start, :center, :end)}} = :start

    aspect_ratio :: Union{Nothing, Float64, Model.EnumType{(:auto,)}} = nothing

    auto_edit :: Bool = false

    autosize_mode :: Model.EnumType{(:fit_columns, :fit_viewport, :force_fit, :none)} = :force_fit

    background :: Union{Nothing, Model.Color} = nothing

    columns :: Vector{iTableColumn} = iTableColumn[]

    css_classes :: Vector{String} = String[]

    default_size :: Int64 = 300

    disabled :: Bool = false

    editable :: Bool = false

    fit_columns :: Union{Nothing, Bool} = nothing

    frozen_columns :: Union{Nothing, Int64} = nothing

    frozen_rows :: Union{Nothing, Int64} = nothing

    header_row :: Bool = true

    height :: Union{Nothing, Model.NonNegativeInt} = 400

    height_policy :: Model.EnumType{(:auto, :fixed, :fit, :min, :max)} = :auto

    index_header :: String = "#"

    index_position :: Union{Nothing, Int64} = 0

    index_width :: Int64 = 40

    margin :: Union{Nothing, NTuple{4, Int64}} = (0, 0, 0, 0)

    max_height :: Union{Nothing, Model.NonNegativeInt} = nothing

    max_width :: Union{Nothing, Model.NonNegativeInt} = nothing

    min_height :: Union{Nothing, Model.NonNegativeInt} = nothing

    min_width :: Union{Nothing, Model.NonNegativeInt} = nothing

    reorderable :: Bool = true

    row_height :: Int64 = 25

    scroll_to_selection :: Bool = true

    selectable :: Union{Bool, Model.EnumType{(:checkbox,)}} = true

    sizing_mode :: Union{Nothing, Model.EnumType{(:stretch_width, :stretch_height, :stretch_both, :scale_width, :scale_height, :scale_both, :fixed)}} = nothing

    sortable :: Bool = true

    source :: iDataSource = ColumnDataSource()

    view :: iCDSView = new(CDSView(; source))

    visible :: Bool = true

    width :: Union{Nothing, Model.NonNegativeInt} = 600

    width_policy :: Model.EnumType{(:auto, :fixed, :fit, :min, :max)} = :auto
end
export DataTable
