#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct DatetimeTickFormatter <: iDatetimeTickFormatter

    context :: Union{Nothing, iDatetimeTickFormatter, String} = nothing

    context_location :: Model.EnumType{(:above, :below, :left, :right)} = :below

    context_which :: Model.EnumType{(:start, :center, :end, :all)} = :start

    days :: String = "%m/%d"

    hourmin :: String = "%H:%M"

    hours :: String = "%Hh"

    microseconds :: String = "%fus"

    milliseconds :: String = "%3Nms"

    minsec :: String = ":%M:%S"

    minutes :: String = ":%M"

    months :: String = "%m/%Y"

    seconds :: String = "%Ss"

    strip_leading_zeros :: Bool = true

    years :: String = "%Y"
end
export DatetimeTickFormatter
