#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Decoration <: iDecoration

    marking :: iMarking

    node :: Model.EnumType{(:start, :middle, :end)} = required
end
export Decoration
