#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Dialog <: iDialog

    buttons :: Vector{iUIElement} = iUIElement[]

    classes :: Vector{String} = String[]

    closable :: Bool = true

    content :: Union{iDOMNode, iUIElement, String} = required

    draggable :: Bool = true

    modal :: Bool = false

    styles :: Union{iStyles, Dict{String, Union{Nothing, String}}} = Dict{String, Union{Nothing, String}}()

    stylesheets :: Vector{Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}} = Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}[]

    title :: Union{Nothing, iDOMNode, String} = nothing

    visible :: Bool = true
end
export Dialog
