#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct DifferenceFilter <: iDifferenceFilter

    operands :: Model.NonEmpty{Vector{iFilter}}
end
export DifferenceFilter
