#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Dodge <: iDodge

    range :: Union{Nothing, iRange} = nothing

    value :: Float64 = 0.0
end
export Dodge
