#- file generated by '/home/pdavezac/code/Bokeh/deps/src/CodeCreator.jl': edit at your own risk! -#

@model mutable struct DOMColorRef <: iDOMColorRef

    field :: String

    hex :: Bool = true

    swatch :: Bool = true
end
