#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct DOMColorRef <: iDOMColorRef

    field :: String = required

    hex :: Bool = true

    swatch :: Bool = true
end
export DOMColorRef
