#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct DOMHTML <: iDOMHTML

    html :: Union{String, Vector{Union{iDOMNode, iUIElement, String}}} = required

    refs :: Vector{Union{iDOMNode, iUIElement, String}} = Union{iDOMNode, iUIElement, String}[]
end
export DOMHTML
