#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct DOMSpan <: iDOMSpan

    children :: Vector{Union{iDOMNode, iLayoutDOM, String}} = Union{iDOMNode, iLayoutDOM, String}[]

    style :: Union{Nothing, iStyles, Dict{String, String}} = nothing
end
