#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct DOMTableRow <: iDOMTableRow

    children :: Vector{Union{iDOMNode, iUIElement, String}} = Union{iDOMNode, iUIElement, String}[]

    style :: Union{Nothing, iStyles, Dict{String, String}} = nothing
end
export DOMTableRow
