#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct DOMTemplate <: iDOMTemplate

    actions :: Vector{iAction} = iAction[]

    children :: Vector{Union{iDOMNode, iLayoutDOM, String}} = Union{iDOMNode, iLayoutDOM, String}[]

    style :: Union{Nothing, iStyles, Dict{String, String}} = nothing
end
