#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct DOMToggleGroup <: iDOMToggleGroup

    groups :: Vector{iRendererGroup} = iRendererGroup[]
end
export DOMToggleGroup
