#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct DOMValueOf <: iDOMValueOf

    attr :: String = required

    obj :: iHasProps = required
end
export DOMValueOf
