#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct EqHistColorMapper <: iEqHistColorMapper

    bins :: Int64 = 65536

    domain :: Vector{Tuple{iGlyphRenderer, Union{String, Vector{String}}}} = Tuple{iGlyphRenderer, Union{String, Vector{String}}}[]

    high :: Model.Nullable{Float64} = nothing

    high_color :: Model.Nullable{Model.Color} = nothing

    low :: Model.Nullable{Float64} = nothing

    low_color :: Model.Nullable{Model.Color} = nothing

    nan_color :: Model.Color = "#808080"

    palette :: Vector{Model.Color}

    rescale_discrete_levels :: Bool = false
end
