#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct FreehandDrawTool <: iFreehandDrawTool

    custom_icon :: Model.Nullable{Model.Image} = nothing

    description :: Model.Nullable{String} = nothing

    empty_value :: Union{Bool, Float64, Int64, Dates.Date, Dates.DateTime, Model.Color, String}

    num_objects :: Int64 = 0

    renderers :: Vector{iGlyphRenderer} = iGlyphRenderer[]
end
