#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct FullscreenTool <: iFullscreenTool

    description :: Union{Nothing, String} = nothing

    icon :: Union{Nothing, Model.ToolIconValue} = nothing
end
export FullscreenTool
