#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct FuncTickFormatter <: iFuncTickFormatter

    args :: Dict{String, Any} = Dict{String, Any}()

    code :: String = ""
end
export FuncTickFormatter
