#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct GeoJSONDataSource <: iGeoJSONDataSource

    geojson :: Model.JSONString

    selected :: Model.ReadOnly{iSelection} = Selection()

    selection_policy :: iSelectionPolicy = UnionRenderers()
end
export GeoJSONDataSource
