#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct GlyphRenderer <: iGlyphRenderer

    coordinates :: Union{Nothing, iCoordinateMapping} = nothing

    data_source :: iDataSource

    glyph :: iGlyph

    group :: Union{Nothing, iRendererGroup} = nothing

    hover_glyph :: Union{Nothing, iGlyph} = nothing

    level :: Model.EnumType{(:image, :underlay, :glyph, :guide, :annotation, :overlay)} = :image

    muted :: Bool = false

    muted_glyph :: Union{Nothing, iGlyph, Model.EnumType{(:auto,)}} = :auto

    nonselection_glyph :: Union{Nothing, iGlyph, Model.EnumType{(:auto,)}} = :auto

    selection_glyph :: Union{Nothing, iGlyph, Model.EnumType{(:auto,)}} = :auto

    view :: iCDSView = new(CDSView(; source = data_source))

    visible :: Bool = true

    x_range_name :: String = "default"

    y_range_name :: String = "default"
end
export GlyphRenderer
