#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct GMapOptions <: iGMapOptions

    lat :: Float64

    lng :: Float64

    map_type :: Model.EnumType{(:satellite, :roadmap, :terrain, :hybrid)} = :roadmap

    scale_control :: Bool = false

    styles :: Model.JSONString

    tilt :: Int64 = 45

    zoom :: Int64 = 12
end
export GMapOptions
