#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct GMapOptions <: iGMapOptions

    lat :: Float64 = required

    lng :: Float64 = required

    map_type :: Model.EnumType{(:satellite, :roadmap, :terrain, :hybrid)} = :roadmap

    scale_control :: Bool = false

    styles :: Union{Nothing, Model.JSONString} = nothing

    tilt :: Int64 = 45

    zoom :: Int64 = 12
end
export GMapOptions
