#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct GraphRenderer <: iGraphRenderer

    coordinates :: Union{Nothing, iCoordinateMapping} = nothing

    edge_renderer :: iGlyphRenderer = GlyphRenderer(; glyph = MultiLine(), data_source = ColumnDataSource(data = Dict("start" => String[], "end" => String[])))

    group :: Union{Nothing, iRendererGroup} = nothing

    inspection_policy :: iGraphHitTestPolicy = NodesOnly()

    layout_provider :: iLayoutProvider

    level :: Model.EnumType{(:image, :underlay, :glyph, :guide, :annotation, :overlay)} = :image

    node_renderer :: iGlyphRenderer = GlyphRenderer(; glyph = Circle(), data_source = ColumnDataSource(data = Dict("index" => String[])))

    selection_policy :: iGraphHitTestPolicy = NodesOnly()

    visible :: Bool = true

    x_range_name :: String = "default"

    y_range_name :: String = "default"
end
export GraphRenderer
