#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct GroupFilter <: iGroupFilter

    column_name :: String = required

    group :: String = required
end
export GroupFilter
