#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct GroupingInfo <: iGroupingInfo

    aggregators :: Vector{iRowAggregator} = iRowAggregator[]

    collapsed :: Bool = false

    getter :: String = ""
end
export GroupingInfo
