#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct HelpTool <: iHelpTool

    description :: Model.Nullable{String} = "Click the question mark to learn more about BokehJL plot tools."

    redirect :: String = "https://docs.bokeh.org/en/latest/docs/user_guide/tools.html"
end
