#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct HTMLTemplateFormatter <: iHTMLTemplateFormatter

    template :: String = "<%= value %>"
end
export HTMLTemplateFormatter
