#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct ImageRGBA <: iImageRGBA

    dh :: Model.DistanceSpec = "dh"

    dh_units :: Model.EnumType{(:screen, :data)} = :data

    dilate :: Bool = false

    dw :: Model.DistanceSpec = "dw"

    dw_units :: Model.EnumType{(:screen, :data)} = :data

    global_alpha :: Model.NumberSpec = 1.0

    image :: Model.NumberSpec = "image"

    x :: Model.NumberSpec = "x"

    y :: Model.NumberSpec = "y"
end
export ImageRGBA
glyphargs(::Type{ImageRGBA}) = (:image, :x, :y, :dw, :dh, :dilate)
