#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Image <: iImage

    color_mapper :: iColorMapper = LinearColorMapper()

    dh :: Model.DistanceSpec = "dh"

    dh_units :: Model.EnumType{(:screen, :data)} = :data

    dilate :: Bool = false

    dw :: Model.DistanceSpec = "dw"

    dw_units :: Model.EnumType{(:screen, :data)} = :data

    global_alpha :: Model.NumberSpec = 1.0

    image :: Model.NumberSpec = "image"

    x :: Model.NumberSpec = "x"

    y :: Model.NumberSpec = "y"
end
export Image
glyphargs(::Type{Image}) = (:image, :x, :y, :dw, :dh, :dilate)
