#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct ImageURL <: iImageURL

    anchor :: Model.EnumType{(:top_left, :top_center, :top_right, :center_left, :center_center, :center_right, :bottom_left, :bottom_center, :bottom_right, :top, :left, :center, :right, :bottom)} = :top_left

    angle :: Model.AngleSpec = 0.0

    decorations :: Vector{iDecoration} = iDecoration[]

    dilate :: Bool = false

    global_alpha :: Model.NumberSpec = 1.0

    h :: Model.NullDistanceSpec = nothing

    retry_attempts :: Int64 = 0

    retry_timeout :: Int64 = 0

    url :: Model.StringSpec = (field = "url",)

    w :: Model.NullDistanceSpec = nothing

    x :: Model.NumberSpec = "x"

    y :: Model.NumberSpec = "y"
end
export ImageURL
glyphargs(::Type{ImageURL}) = (:url, :x, :y, :w, :h, :angle, :dilate)
