#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct ImageURLTexture <: iImageURLTexture

    repetition :: Model.EnumType{(:repeat, :repeat_x, :repeat_y, :no_repeat)} = :repeat

    url :: String
end
export ImageURLTexture
