#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct IndexFilter <: iIndexFilter

    indices :: Union{Nothing, Vector{Int64}} = nothing
end
export IndexFilter
