#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Inspector <: iInspector

    classes :: Vector{String} = String[]

    styles :: Union{iStyles, Dict{String, Union{Nothing, String}}} = Dict{String, Union{Nothing, String}}()

    stylesheets :: Vector{Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}} = Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}[]

    target :: Union{Nothing, iHasProps} = nothing

    visible :: Bool = true
end
export Inspector
