#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct IntersectionFilter <: iIntersectionFilter

    operands :: Model.NonEmpty{Vector{iFilter}}
end
export IntersectionFilter
