#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct LassoSelectTool <: iLassoSelectTool

    description :: Union{Nothing, String} = nothing

    mode :: Model.EnumType{(:replace, :append, :intersect, :subtract)} = :replace

    names :: Vector{String} = String[]

    overlay :: iPolyAnnotation = PolyAnnotation()

    renderers :: Union{Model.EnumType{(:auto,)}, Vector{iDataRenderer}} = :auto

    select_every_mousemove :: Bool = true
end
export LassoSelectTool
