#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct LinearInterpolator <: iLinearInterpolator

    clip :: Bool = true

    data :: Union{Nothing, iColumnarDataSource} = nothing

    x :: Union{String, Vector{Float64}} = required

    y :: Union{String, Vector{Float64}} = required
end
export LinearInterpolator
