#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Menu <: iMenu

    classes :: Vector{String} = String[]

    items :: Vector{iMenuItem} = iMenuItem[]

    orientation :: Model.EnumType{(:horizontal, :vertical)} = :vertical

    reversed :: Bool = false

    styles :: Union{iStyles, Dict{String, Union{Nothing, String}}} = Dict{String, Union{Nothing, String}}()

    stylesheets :: Vector{Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}} = Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}[]

    visible :: Bool = true
end
export Menu
