#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct Minimum <: iMinimum

    field :: String

    initial :: Union{Nothing, Float64} = nothing
end
export Minimum
