#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct MultiChoice <: iMultiChoice

    align :: Union{Tuple{Model.EnumType{(:start, :center, :end)}, Model.EnumType{(:start, :center, :end)}}, Model.EnumType{(:start, :center, :end)}} = :start

    aspect_ratio :: Union{Nothing, Float64, Model.EnumType{(:auto,)}} = nothing

    background :: Union{Nothing, Model.Color} = nothing

    css_classes :: Vector{String} = String[]

    default_size :: Int64 = 300

    delete_button :: Bool = true

    disabled :: Bool = false

    height :: Union{Nothing, Model.NonNegativeInt} = nothing

    height_policy :: Model.EnumType{(:auto, :fixed, :fit, :min, :max)} = :auto

    margin :: Union{Nothing, NTuple{4, Int64}} = (0, 0, 0, 0)

    max_height :: Union{Nothing, Model.NonNegativeInt} = nothing

    max_items :: Union{Nothing, Int64} = nothing

    max_width :: Union{Nothing, Model.NonNegativeInt} = nothing

    min_height :: Union{Nothing, Model.NonNegativeInt} = nothing

    min_width :: Union{Nothing, Model.NonNegativeInt} = nothing

    option_limit :: Union{Nothing, Int64} = nothing

    options :: Vector{Union{String, Tuple{String, String}}} = Union{String, Tuple{String, String}}[]

    placeholder :: Union{Nothing, String} = nothing

    search_option_limit :: Union{Nothing, Int64} = nothing

    sizing_mode :: Union{Nothing, Model.EnumType{(:stretch_width, :stretch_height, :stretch_both, :scale_width, :scale_height, :scale_both, :fixed)}} = nothing

    solid :: Bool = true

    title :: String = ""

    value :: Vector{String} = String[]

    visible :: Bool = true

    width :: Union{Nothing, Model.NonNegativeInt} = nothing

    width_policy :: Model.EnumType{(:auto, :fixed, :fit, :min, :max)} = :auto
end
