#- file generated by '/home/pdavezac/code/Bokeh/deps/src/CodeCreator.jl': edit at your own risk! -#

@model mutable struct OpenURL <: iOpenURL

    same_tab :: Bool = false

    url :: String = "http://"
end
