#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct PanTool <: iPanTool

    description :: Model.Nullable{String} = nothing

    dimensions :: Model.EnumType{(:width, :height, :both)} = :both
end
