#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Patch <: iPatch

    fill_alpha :: Model.Percent = 1.0

    fill_color :: Union{Nothing, Model.Color} = "#808080"

    hatch_alpha :: Model.Percent = 1.0

    hatch_color :: Union{Nothing, Model.Color} = "#000000"

    hatch_extra :: Dict{String, iTexture} = Dict{String, iTexture}()

    hatch_pattern :: Union{Nothing, String} = nothing

    hatch_scale :: Model.Size = 12.0

    hatch_weight :: Model.Size = 1.0

    line_alpha :: Model.Percent = 1.0

    line_cap :: Model.LineCap = :butt

    line_color :: Union{Nothing, Model.Color} = "#000000"

    line_dash :: Model.DashPattern = Int64[]

    line_dash_offset :: Int64 = 0

    line_join :: Model.LineJoin = :bevel

    line_width :: Float64 = 1.0

    x :: Model.NumberSpec = "x"

    y :: Model.NumberSpec = "y"
end
export Patch
glyphargs(::Type{Patch}) = (:x, :y)
