#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct PolyDrawTool <: iPolyDrawTool

    custom_icon :: Union{Nothing, Model.Image} = nothing

    description :: Union{Nothing, String} = nothing

    drag :: Bool = true

    empty_value :: Union{Bool, Float64, Int64, Dates.Date, Dates.DateTime, Model.Color, String}

    num_objects :: Int64 = 0

    renderers :: Vector{iGlyphRenderer} = iGlyphRenderer[]

    vertex_renderer :: Union{Nothing, iGlyphRenderer} = nothing
end
export PolyDrawTool
