#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct PolyEditTool <: iPolyEditTool

    description :: Union{Nothing, String} = nothing

    empty_value :: Union{Bool, Float64, Int64, Dates.Date, Dates.DateTime, Model.Color, String}

    icon :: Union{Nothing, Model.ToolIconValue} = nothing

    renderers :: Vector{iGlyphRenderer} = iGlyphRenderer[]

    vertex_renderer :: Union{Nothing, iGlyphRenderer} = nothing
end
export PolyEditTool
