#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct PolySelectTool <: iPolySelectTool

    description :: Union{Nothing, String} = nothing

    mode :: Model.EnumType{(:replace, :append, :intersect, :subtract)} = :replace

    names :: Vector{String} = String[]

    overlay :: iPolyAnnotation = PolyAnnotation()

    renderers :: Union{Model.EnumType{(:auto,)}, Vector{iDataRenderer}} = :auto
end
