#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct PrintfTickFormatter <: iPrintfTickFormatter

    format :: String = "%s"
end
export PrintfTickFormatter
