#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct ServerSentDataSource <: iServerSentDataSource

    adapter :: Union{Nothing, iCustomJS} = nothing

    data :: Model.DataDict = Model.DataDict()

    data_url :: String

    max_size :: Union{Nothing, Int64} = nothing

    mode :: Model.EnumType{(:replace, :append)} = :replace

    selected :: Model.ReadOnly{iSelection} = Selection()

    selection_policy :: iSelectionPolicy = UnionRenderers()
end
