#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct SetValue <: iSetValue

    attr :: String = required

    obj :: iHasProps = required

    value :: Any = required
end
export SetValue
