#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct SetValue <: iSetValue

    attr :: String

    obj :: iHasProps

    value :: Any
end
export SetValue
