#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct SingleIntervalTicker <: iSingleIntervalTicker

    desired_num_ticks :: Int64 = 6

    interval :: Float64 = required

    num_minor_ticks :: Int64 = 5
end
export SingleIntervalTicker
