#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct StaticLayoutProvider <: iStaticLayoutProvider

    graph_layout :: Dict{Union{Int64, String}, Vector{Any}} = Dict{Union{Int64, String}, Vector{Any}}()
end
export StaticLayoutProvider
