#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct StaticLayoutProvider <: iStaticLayoutProvider

    graph_layout :: Dict{Int64, Vector{Any}} = Dict{Int64, Vector{Any}}()
end
export StaticLayoutProvider
