#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Step <: iStep

    line_alpha :: Model.Percent = 1.0

    line_cap :: Model.LineCap = :butt

    line_color :: Union{Nothing, Model.Color} = "#000000"

    line_dash :: Model.DashPattern = Int64[]

    line_dash_offset :: Int64 = 0

    line_join :: Model.LineJoin = :bevel

    line_width :: Float64 = 1.0

    mode :: Model.EnumType{(:before, :after, :center)} = :before

    x :: Model.NumberSpec = "x"

    y :: Model.NumberSpec = "y"
end
export Step
glyphargs(::Type{Step}) = (:x, :y)
