#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct StringFormatter <: iStringFormatter

    font_style :: Model.FontStyle = :normal

    nan_format :: String = "-"

    text_align :: Model.TextAlign = :left

    text_color :: Union{Nothing, Model.Color} = nothing
end
export StringFormatter
