#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct SVGIcon <: iSVGIcon

    size :: Union{Model.FontSize, Int64} = "1em"

    svg :: String
end
export SVGIcon
