#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct SymmetricDifferenceFilter <: iSymmetricDifferenceFilter

    operands :: Model.NonEmpty{Vector{iFilter}} = required
end
export SymmetricDifferenceFilter
