#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct TablerIcon <: iTablerIcon

    icon_name :: String = required

    size :: Union{Model.FontSize, Int64} = "1em"
end
export TablerIcon
