#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct TabPanel <: iTabPanel

    child :: iUIElement

    closable :: Bool = false

    disabled :: Bool = false

    title :: String = ""
end
export TabPanel
