#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct TapTool <: iTapTool

    behavior :: Model.EnumType{(:select, :inspect)} = :select

    callback :: Union{Nothing, iCallback} = nothing

    description :: Union{Nothing, String} = nothing

    gesture :: Model.EnumType{(:tap, :doubletap)} = :tap

    icon :: Union{Nothing, Model.ToolIconValue} = nothing

    mode :: Model.EnumType{(:replace, :append, :intersect, :subtract)} = :replace

    renderers :: Union{Model.EnumType{(:auto,)}, Vector{iDataRenderer}} = :auto
end
export TapTool
