#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct TileRenderer <: iTileRenderer

    alpha :: Float64 = 1.0

    coordinates :: Union{Nothing, iCoordinateMapping} = nothing

    group :: Union{Nothing, iRendererGroup} = nothing

    level :: Model.EnumType{(:image, :underlay, :glyph, :guide, :annotation, :overlay)} = :image

    render_parents :: Bool = true

    smoothing :: Bool = true

    tile_source :: iTileSource = WMTSTileSource()

    visible :: Bool = true

    x_range_name :: String = "default"

    y_range_name :: String = "default"
end
export TileRenderer
