#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Tooltip <: iTooltip

    attachment :: Model.EnumType{(:horizontal, :vertical, :left, :right, :above, :below, :auto)} = :auto

    classes :: Vector{String} = String[]

    closable :: Bool = false

    content :: Union{iDOMHTML, String} = required

    interactive :: Bool = true

    position :: Union{Nothing, Tuple{Float64, Float64}, Model.EnumType{(:top_left, :top_center, :top_right, :center_left, :center_center, :center_right, :bottom_left, :bottom_center, :bottom_right, :top, :left, :center, :right, :bottom)}} = nothing

    show_arrow :: Bool = true

    styles :: Union{iStyles, Dict{String, Union{Nothing, String}}} = Dict{String, Union{Nothing, String}}()

    stylesheets :: Vector{Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}} = Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}[]

    target :: Union{iSelector, iUIElement, Model.EnumType{(:auto,)}} = :auto

    visible :: Bool = false
end
export Tooltip
