#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Toolbar <: iToolbar

    active_drag :: Union{Nothing, iDrag, Model.EnumType{(:auto,)}} = :auto

    active_inspect :: Union{Nothing, iInspectTool, Model.EnumType{(:auto,)}, Vector{iInspectTool}} = :auto

    active_multi :: Union{Nothing, iGestureTool, Model.EnumType{(:auto,)}} = :auto

    active_scroll :: Union{Nothing, iScroll, Model.EnumType{(:auto,)}} = :auto

    active_tap :: Union{Nothing, iTap, Model.EnumType{(:auto,)}} = :auto

    autohide :: Bool = false

    classes :: Vector{String} = String[]

    logo :: Union{Nothing, Model.EnumType{(:normal, :grey)}} = :normal

    styles :: Union{iStyles, Dict{String, Union{Nothing, String}}} = Dict{String, Union{Nothing, String}}()

    stylesheets :: Vector{Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}} = Union{Dict{String, Union{iStyles, Dict{String, Union{Nothing, String}}}}, String}[]

    tools :: Vector{Union{iTool, iToolProxy}} = Union{iTool, iToolProxy}[]

    visible :: Bool = true
end
export Toolbar
