#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct ToolProxy <: iToolProxy

    active :: Bool = false

    disabled :: Bool = false

    tools :: Vector{iTool} = iTool[]
end
export ToolProxy
