#- file generated by BokehJL's 'CodeCreator': edit at your own risk! -#

@model mutable struct ToolbarPanel <: iToolbarPanel

    coordinates :: Union{Nothing, iCoordinateMapping} = nothing

    group :: Union{Nothing, iRendererGroup} = nothing

    level :: Model.EnumType{(:image, :underlay, :glyph, :guide, :annotation, :overlay)} = :image

    toolbar :: iToolbar

    visible :: Bool = true

    x_range_name :: String = "default"

    y_range_name :: String = "default"
end
