#- file generated by '/home/pdavezac/code/Bokeh/deps/src/CodeCreator.jl': edit at your own risk! -#

@model mutable struct UndoTool <: iUndoTool

    description :: Model.Nullable{String} = nothing
end
