#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct VArea <: iVArea

    decorations :: Vector{iDecoration} = iDecoration[]

    fill_alpha :: Model.Percent = 1.0

    fill_color :: Union{Nothing, Model.Color} = "#808080"

    hatch_alpha :: Model.AlphaSpec = 1.0

    hatch_color :: Model.ColorSpec = "#000000"

    hatch_extra :: Dict{String, iTexture} = Dict{String, iTexture}()

    hatch_pattern :: Model.HatchPatternSpec = :blank

    hatch_scale :: Model.NumberSpec = 12.0

    hatch_weight :: Model.NumberSpec = 1.0

    x :: Model.NumberSpec = "x"

    y1 :: Model.NumberSpec = "y1"

    y2 :: Model.NumberSpec = "y2"
end
export VArea
glyphargs(::Type{VArea}) = (:x, :y1, :y2)
