#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct VBar <: iVBar

    bottom :: Model.NumberSpec = 0.0

    decorations :: Vector{iDecoration} = iDecoration[]

    fill_alpha :: Model.AlphaSpec = 1.0

    fill_color :: Model.ColorSpec = "#808080"

    hatch_alpha :: Model.AlphaSpec = 1.0

    hatch_color :: Model.ColorSpec = "#000000"

    hatch_extra :: Dict{String, iTexture} = Dict{String, iTexture}()

    hatch_pattern :: Model.HatchPatternSpec = :blank

    hatch_scale :: Model.NumberSpec = 12.0

    hatch_weight :: Model.NumberSpec = 1.0

    line_alpha :: Model.AlphaSpec = 1.0

    line_cap :: Model.LineCapSpec = :butt

    line_color :: Model.ColorSpec = "#000000"

    line_dash :: Model.DashPatternSpec = Int64[]

    line_dash_offset :: Model.IntSpec = 0

    line_join :: Model.LineJoinSpec = :bevel

    line_width :: Model.NumberSpec = 1.0

    top :: Model.NumberSpec = "top"

    width :: Model.NumberSpec = 1.0

    x :: Model.NumberSpec = "x"
end
export VBar
glyphargs(::Type{VBar}) = (:x, :width, :top, :bottom)
