#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct Whisker <: iWhisker

    base :: Model.UnitsSpec = "base"

    coordinates :: Union{Nothing, iCoordinateMapping} = nothing

    dimension :: Model.EnumType{(:width, :height)} = :height

    group :: Union{Nothing, iRendererGroup} = nothing

    level :: Model.EnumType{(:image, :underlay, :glyph, :guide, :annotation, :overlay)} = :underlay

    line_alpha :: Model.AlphaSpec = 1.0

    line_cap :: Model.LineCapSpec = :butt

    line_color :: Model.ColorSpec = "#000000"

    line_dash :: Model.DashPatternSpec = Int64[]

    line_dash_offset :: Model.IntSpec = 0

    line_join :: Model.LineJoinSpec = :bevel

    line_width :: Model.NumberSpec = 1.0

    lower :: Model.UnitsSpec = "lower"

    lower_head :: Union{Nothing, iArrowHead} = TeeHead(size = 10)

    source :: iDataSource = ColumnDataSource()

    upper :: Model.UnitsSpec = "upper"

    upper_head :: Union{Nothing, iArrowHead} = TeeHead(size = 10)

    visible :: Bool = true

    x_range_name :: String = "default"

    y_range_name :: String = "default"
end
export Whisker
