#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct ZoomOutTool <: iZoomOutTool

    description :: Union{Nothing, String} = nothing

    dimensions :: Model.EnumType{(:width, :height, :both)} = :both

    factor :: Model.Percent = 0.1

    icon :: Union{Nothing, Model.ToolIconValue} = nothing

    maintain_focus :: Bool = true
end
export ZoomOutTool
