#- file generated by BokehServer's 'CodeCreator': edit at your own risk! -#

@model mutable struct ZoomInTool <: iZoomInTool

    description :: Union{Nothing, String} = nothing

    dimensions :: Model.EnumType{(:width, :height, :both)} = :both

    factor :: Model.Percent = 0.1

    icon :: Union{Nothing, Model.ToolIconValue} = nothing
end
export ZoomInTool
