#- file created by '/home/pdavezac/code/Bokeh/deps/src/CodeCreator.jl': edit at your own risk! -#
module ModelTypes
using ..AbstractTypes
abstract type iTicker <: iModel end
abstract type iContinuousTicker <: iTicker end
abstract type iDOMNode <: iModel end
abstract type iDOMElement <: iDOMNode end
abstract type iDOMSpan <: iDOMElement end
abstract type iTool <: iModel end
abstract type iGestureTool <: iTool end
abstract type iSelectTool <: iGestureTool end
abstract type iAbstractIcon <: iModel end
abstract type iGlyph <: iModel end
abstract type iXYGlyph <: iGlyph end
abstract type iImageRGBA <: iXYGlyph end
abstract type iLegendItem <: iModel end
abstract type iRenderer <: iModel end
abstract type iAnnotation <: iRenderer end
abstract type iPolyAnnotation <: iAnnotation end
abstract type iSingleIntervalTicker <: iContinuousTicker end
abstract type iYearsTicker <: iSingleIntervalTicker end
abstract type iActionTool <: iTool end
abstract type iHelpTool <: iActionTool end
abstract type iArrowHead <: iModel end
abstract type iNormalHead <: iArrowHead end
abstract type iText <: iGlyph end
abstract type iDrag <: iGestureTool end
abstract type iPanTool <: iDrag end
abstract type iInspectTool <: iGestureTool end
abstract type iHoverTool <: iInspectTool end
abstract type iFillGlyph <: iGlyph end
abstract type iCellEditor <: iModel end
abstract type iStringEditor <: iCellEditor end
abstract type iMapOptions <: iModel end
abstract type iGMapOptions <: iMapOptions end
abstract type iTransform <: iModel end
abstract type iScale <: iTransform end
abstract type iWedge <: iGlyph end
abstract type iLayoutDOM <: iModel end
abstract type iWidget <: iLayoutDOM end
abstract type iTableWidget <: iWidget end
abstract type iDataTable <: iTableWidget end
abstract type iTileSource <: iModel end
abstract type iMercatorTileSource <: iTileSource end
abstract type iTMSTileSource <: iMercatorTileSource end
abstract type iTableColumn <: iModel end
abstract type iScroll <: iGestureTool end
abstract type iRowAggregator <: iModel end
abstract type iBaseText <: iModel end
abstract type iPlainText <: iBaseText end
abstract type iPlaceholder <: iDOMNode end
abstract type iValueRef <: iPlaceholder end
abstract type iDOMColorRef <: iValueRef end
abstract type iConnectedXYGlyph <: iXYGlyph end
abstract type iTickFormatter <: iModel end
abstract type iBasicTickFormatter <: iTickFormatter end
abstract type iMercatorTickFormatter <: iBasicTickFormatter end
abstract type iGraphHitTestPolicy <: iModel end
abstract type iExpression <: iModel end
abstract type iXYComponent <: iExpression end
abstract type iXComponent <: iXYComponent end
abstract type iTextAnnotation <: iAnnotation end
abstract type iLabel <: iTextAnnotation end
abstract type iAbstractSlider <: iWidget end
abstract type iDateSlider <: iAbstractSlider end
abstract type iInputWidget <: iWidget end
abstract type iYComponent <: iXYComponent end
abstract type iSpacer <: iLayoutDOM end
abstract type iJitter <: iTransform end
abstract type iZoomOutTool <: iActionTool end
abstract type iAbstractGroup <: iWidget end
abstract type iDataSource <: iModel end
abstract type iColumnarDataSource <: iDataSource end
abstract type iColumnDataSource <: iColumnarDataSource end
abstract type iDaysTicker <: iSingleIntervalTicker end
abstract type iHexTile <: iGlyph end
abstract type iBox <: iLayoutDOM end
abstract type iColumn <: iBox end
abstract type iWidgetBox <: iColumn end
abstract type iContinuousScale <: iScale end
abstract type iLinearScale <: iContinuousScale end
abstract type iMarker <: iGlyph end
abstract type iCircle <: iMarker end
abstract type iFileInput <: iWidget end
abstract type iRedoTool <: iActionTool end
abstract type iNodesAndLinkedEdges <: iGraphHitTestPolicy end
abstract type iMapper <: iTransform end
abstract type iCategoricalColorMapper <: iMapper end
abstract type iMultiPolygons <: iGlyph end
abstract type iCumSum <: iExpression end
abstract type iSlider <: iAbstractSlider end
abstract type iPatch <: iGlyph end
abstract type iMultiChoice <: iInputWidget end
abstract type iSpan <: iAnnotation end
abstract type iBoxAnnotation <: iAnnotation end
abstract type iTextLikeInput <: iInputWidget end
abstract type iTextAreaInput <: iTextLikeInput end
abstract type iGuideRenderer <: iRenderer end
abstract type iAxis <: iGuideRenderer end
abstract type iContinuousAxis <: iAxis end
abstract type iLinearAxis <: iContinuousAxis end
abstract type iAnnularWedge <: iGlyph end
abstract type iDOMTemplate <: iDOMElement end
abstract type iCategoricalTickFormatter <: iTickFormatter end
abstract type iDatetimeRangeSlider <: iAbstractSlider end
abstract type iCoordinateTransform <: iExpression end
abstract type iGraphCoordinates <: iCoordinateTransform end
abstract type iNodeCoordinates <: iGraphCoordinates end
abstract type iRangeTool <: iDrag end
abstract type iNumberEditor <: iCellEditor end
abstract type iPlot <: iLayoutDOM end
abstract type iMapPlot <: iPlot end
abstract type iGMapPlot <: iMapPlot end
abstract type iCrosshairTool <: iInspectTool end
abstract type iCellFormatter <: iModel end
abstract type iBooleanFormatter <: iCellFormatter end
abstract type iEllipse <: iGlyph end
abstract type iBoxZoomTool <: iDrag end
abstract type iColorMapper <: iMapper end
abstract type iDataAnnotation <: iAnnotation end
abstract type iArrow <: iDataAnnotation end
abstract type iDOMDiv <: iDOMElement end
abstract type iTexture <: iModel end
abstract type iCanvasTexture <: iTexture end
abstract type iOval <: iGlyph end
abstract type iLabelingPolicy <: iModel end
abstract type iAllLabels <: iLabelingPolicy end
abstract type iGeoJSONDataSource <: iColumnarDataSource end
abstract type iMinAggregator <: iRowAggregator end
abstract type iDOMPlaceholder <: iDOMNode end
abstract type iMaxAggregator <: iRowAggregator end
abstract type iMathText <: iBaseText end
abstract type iTileRenderer <: iRenderer end
abstract type iImageURL <: iXYGlyph end
abstract type iMarkup <: iWidget end
abstract type iParagraph <: iMarkup end
abstract type iPreText <: iParagraph end
abstract type iAbstractButton <: iWidget end
abstract type iDropdown <: iAbstractButton end
abstract type iTextInput <: iTextLikeInput end
abstract type iAutocompleteInput <: iTextInput end
abstract type iAscii <: iMathText end
abstract type iFilter <: iModel end
abstract type iIndexFilter <: iFilter end
abstract type iPrintfTickFormatter <: iTickFormatter end
abstract type iCDSView <: iModel end
abstract type iCustomJSExpr <: iExpression end
abstract type iToolbarPanel <: iAnnotation end
abstract type iCallback <: iModel end
abstract type iCustomJSTransform <: iTransform end
abstract type iStringFormatter <: iCellFormatter end
abstract type iNumberFormatter <: iStringFormatter end
abstract type iContinuousColorMapper <: iColorMapper end
abstract type iRange <: iModel end
abstract type iRange1d <: iRange end
abstract type iPolarTransform <: iCoordinateTransform end
abstract type iVeeHead <: iArrowHead end
abstract type iLinearColorMapper <: iContinuousColorMapper end
abstract type iSelection <: iModel end
abstract type iStep <: iGlyph end
abstract type iNumericInput <: iInputWidget end
abstract type iSpinner <: iNumericInput end
abstract type iScalarExpression <: iModel end
abstract type iMinimum <: iScalarExpression end
abstract type iHatchGlyph <: iGlyph end
abstract type iDOMTable <: iDOMElement end
abstract type iButtonGroup <: iAbstractGroup end
abstract type iRadioButtonGroup <: iButtonGroup end
abstract type iTextGlyph <: iGlyph end
abstract type iCompositeTicker <: iContinuousTicker end
abstract type iBand <: iDataAnnotation end
abstract type iRay <: iGlyph end
abstract type iSelectionPolicy <: iModel end
abstract type iUnionRenderers <: iSelectionPolicy end
abstract type iLineEditTool <: iGestureTool end
abstract type iTitle <: iTextAnnotation end
abstract type iRendererGroup <: iModel end
abstract type iCategoricalMapper <: iMapper end
abstract type iCategoricalMarkerMapper <: iCategoricalMapper end
abstract type iAction <: iModel end
abstract type iDOMToggleGroup <: iAction end
abstract type iFixedTicker <: iContinuousTicker end
abstract type iPasswordInput <: iTextInput end
abstract type iWebDataSource <: iColumnDataSource end
abstract type iServerSentDataSource <: iWebDataSource end
abstract type iQUADKEYTileSource <: iMercatorTileSource end
abstract type iCheckboxButtonGroup <: iButtonGroup end
abstract type iAdaptiveTicker <: iContinuousTicker end
abstract type iLogTicker <: iAdaptiveTicker end
abstract type iEdgeCoordinates <: iGraphCoordinates end
abstract type iCategoricalAxis <: iAxis end
abstract type iStyles <: iModel end
abstract type iTimeEditor <: iCellEditor end
abstract type iSaveTool <: iActionTool end
abstract type iDatetimeAxis <: iLinearAxis end
abstract type iInterpolator <: iTransform end
abstract type iLinearInterpolator <: iInterpolator end
abstract type iDOMValueRef <: iPlaceholder end
abstract type iToolbarBox <: iLayoutDOM end
abstract type iCheckboxEditor <: iCellEditor end
abstract type iImage <: iXYGlyph end
abstract type iVBar <: iGlyph end
abstract type iLineGlyph <: iGlyph end
abstract type iTooltip <: iAnnotation end
abstract type iDOMTableRow <: iDOMElement end
abstract type iGroup <: iAbstractGroup end
abstract type iQuad <: iGlyph end
abstract type iPanel <: iModel end
abstract type iUndoTool <: iActionTool end
abstract type iToggle <: iAbstractButton end
abstract type iTap <: iGestureTool end
abstract type iCoordinateMapping <: iModel end
abstract type iDataModel <: iModel end
abstract type iArc <: iGlyph end
abstract type iDataRange <: iRange end
abstract type iScientificFormatter <: iStringFormatter end
abstract type iVArea <: iGlyph end
abstract type iNoOverlap <: iLabelingPolicy end
abstract type iMathML <: iMathText end
abstract type iBasicTicker <: iAdaptiveTicker end
abstract type iDataRenderer <: iRenderer end
abstract type iGraphRenderer <: iDataRenderer end
abstract type iMaximum <: iScalarExpression end
abstract type iDatePicker <: iInputWidget end
abstract type iCustomJS <: iCallback end
abstract type iColorBar <: iAnnotation end
abstract type iToolbarBase <: iModel end
abstract type iToolbar <: iToolbarBase end
abstract type iEditTool <: iGestureTool end
abstract type iHTMLBox <: iLayoutDOM end
abstract type iLogColorMapper <: iContinuousColorMapper end
abstract type iPolyDrawTool <: iGestureTool end
abstract type iSumAggregator <: iRowAggregator end
abstract type iOpenHead <: iArrowHead end
abstract type iPatches <: iGlyph end
abstract type iCategoricalPatternMapper <: iCategoricalMapper end
abstract type iLabelSet <: iDataAnnotation end
abstract type iBezier <: iLineGlyph end
abstract type iDateFormatter <: iStringFormatter end
abstract type iPointDrawTool <: iGestureTool end
abstract type iBinnedTicker <: iTicker end
abstract type iDOMAction <: iModel end
abstract type iHArea <: iGlyph end
abstract type iWhisker <: iDataAnnotation end
abstract type iLassoSelectTool <: iGestureTool end
abstract type iButton <: iAbstractButton end
abstract type iNodesOnly <: iGraphHitTestPolicy end
abstract type iTextEditor <: iCellEditor end
abstract type iTapTool <: iGestureTool end
abstract type iLayoutProvider <: iModel end
abstract type iStaticLayoutProvider <: iLayoutProvider end
abstract type iDataRange1d <: iDataRange end
abstract type iDOMIndex <: iPlaceholder end
abstract type iBooleanFilter <: iFilter end
abstract type iDatetimeTicker <: iCompositeTicker end
abstract type iStack <: iExpression end
abstract type iDodge <: iTransform end
abstract type iQuadratic <: iLineGlyph end
abstract type iColorPicker <: iInputWidget end
abstract type iLegend <: iAnnotation end
abstract type iGroupingInfo <: iModel end
abstract type iCustomAction <: iActionTool end
abstract type iBoxEditTool <: iGestureTool end
abstract type iPolyTool <: iEditTool end
abstract type iCustomJSHover <: iModel end
abstract type iIntersectRenderers <: iSelectionPolicy end
abstract type iWheelPanTool <: iScroll end
abstract type iSelectEditor <: iCellEditor end
abstract type iFactorRange <: iRange end
abstract type iTeeHead <: iArrowHead end
abstract type iHTMLTemplateFormatter <: iCellFormatter end
abstract type iScanningColorMapper <: iContinuousColorMapper end
abstract type iEqHistColorMapper <: iScanningColorMapper end
abstract type iLogAxis <: iContinuousAxis end
abstract type iGroupFilter <: iFilter end
abstract type iAjaxDataSource <: iWebDataSource end
abstract type iWheelZoomTool <: iScroll end
abstract type iDateRangeSlider <: iAbstractSlider end
abstract type iMercatorTicker <: iBasicTicker end
abstract type iHBar <: iGlyph end
abstract type iDateEditor <: iCellEditor end
abstract type iMultiLine <: iLineGlyph end
abstract type iScatter <: iMarker end
abstract type iCustomJSFilter <: iFilter end
abstract type iResetTool <: iActionTool end
abstract type iRadioGroup <: iGroup end
abstract type iRangeSlider <: iAbstractSlider end
abstract type iTabs <: iLayoutDOM end
abstract type iGlyphRenderer <: iDataRenderer end
abstract type iBBoxTileSource <: iMercatorTileSource end
abstract type iEdgesAndLinkedNodes <: iGraphHitTestPolicy end
abstract type iPercentEditor <: iCellEditor end
abstract type iSlope <: iAnnotation end
abstract type iRect <: iGlyph end
abstract type iAnnulus <: iGlyph end
abstract type iFuncTickFormatter <: iTickFormatter end
abstract type iProxyToolbar <: iToolbarBase end
abstract type iImageURLTexture <: iTexture end
abstract type iOpenURL <: iCallback end
abstract type iCategoricalTicker <: iTicker end
abstract type iIntEditor <: iCellEditor end
abstract type iSelect <: iInputWidget end
abstract type iWMTSTileSource <: iMercatorTileSource end
abstract type iAvgAggregator <: iRowAggregator end
abstract type iLine <: iGlyph end
abstract type iMultiSelect <: iInputWidget end
abstract type iLogTickFormatter <: iTickFormatter end
abstract type iGridBox <: iLayoutDOM end
abstract type iZoomInTool <: iActionTool end
abstract type iBoxSelectTool <: iGestureTool end
abstract type iRow <: iBox end
abstract type iPolySelectTool <: iGestureTool end
abstract type iGrid <: iGuideRenderer end
abstract type iNumeralTickFormatter <: iTickFormatter end
abstract type iEdgesOnly <: iGraphHitTestPolicy end
abstract type iFreehandDrawTool <: iGestureTool end
abstract type iCategoricalScale <: iScale end
abstract type iMercatorAxis <: iLinearAxis end
abstract type iCheckboxGroup <: iGroup end
abstract type iSegment <: iLineGlyph end
abstract type iDatetimeTickFormatter <: iTickFormatter end
abstract type iPolyEditTool <: iGestureTool end
abstract type iStepInterpolator <: iInterpolator end
abstract type iDOMText <: iDOMNode end
abstract type iDataCube <: iDataTable end
abstract type iMonthsTicker <: iSingleIntervalTicker end
abstract type iCustomLabelingPolicy <: iLabelingPolicy end
abstract type iDiv <: iMarkup end
abstract type iLogScale <: iContinuousScale end
abstract type iTeX <: iMathText end
end
